export const banks = [
    {
      id: "1",
      title: "First National Bank",
      email: "contact@fnb.com",
      password: "securePass123",
      description: "One of the oldest banks in the country with global presence.",
      address: "123 Elm Street",
      city: "New York",
      phone: "+1 212-555-0101",
      status: "approved",
      createdAt: "2024-12-10T10:00:00Z",
    },
    {
      id: "2",
      title: "Global Trust Bank",
      email: "support@gtb.com",
      password: "gtbpass456",
      description: "A bank you can trust for international transactions.",
      address: "456 Oak Avenue",
      city: "Los Angeles",
      phone: "+1 310-555-0202",
      status: "pending",
      createdAt: "2025-01-15T14:25:00Z",
    },
    {
      id: "3",
      title: "Metro Credit Union",
      email: "hello@metrocu.org",
      password: "metro789",
      description: "Serving local communities with personal banking services.",
      address: "789 Pine Road",
      city: "Chicago",
      phone: "+1 773-555-0303",
      status: "rejected",
      createdAt: "2025-03-22T08:45:00Z",
    },
    {
      id: "4",
      title: "Metro Credit Union",
      email: "hello@metrocu.org",
      password: "metro789",
      description: "Serving local communities with personal banking services.",
      address: "789 Pine Road",
      city: "Chicago",
      phone: "+1 773-555-0303",
      status: "rejected",
      createdAt: "2025-03-22T08:45:00Z",
    },
    {
      id: "5",
      title: "United Finance",
      email: "info5@unitedfinance.com",
      password: "pass5@",
      description: "Dedicated to personal and business banking excellence.",
      address: "422 Maple Street",
      city: "Philadelphia",
      phone: "+1 970-555-7329",
      status: "pending",
      createdAt: "2025-04-26T08:00:00Z",
    },
    {
      id: "6",
      title: "Alliance Bank",
      email: "info6@alliancebank.com",
      password: "pass6#",
      description: "Dedicated to personal and business banking excellence.",
      address: "710 Pine Street",
      city: "Phoenix",
      phone: "+1 267-555-3558",
      status: "pending",
      createdAt: "2025-03-28T21:00:00Z",
    },
    {
      id: "7",
      title: "Global Trust Bank",
      email: "info7@globaltrustbank.com",
      password: "pass7!",
      description: "Rooted in tradition, focused on the future.",
      address: "149 Oak Street",
      city: "San Antonio",
      phone: "+1 398-555-3423",
      status: "approved",
      createdAt: "2024-12-13T08:00:00Z",
    },
    {
      id: "8",
      title: "Evergreen Bank",
      email: "info8@evergreenbank.com",
      password: "pass8@",
      description: "Committed to transparency and innovation.",
      address: "894 Elm Street",
      city: "Houston",
      phone: "+1 683-555-1629",
      status: "approved",
      createdAt: "2025-02-23T02:00:00Z",
    },
    {
      id: "9",
      title: "Summit Bank",
      email: "info9@summitbank.com",
      password: "pass9#",
      description: "Trusted partner in local and international finance.",
      address: "512 Pine Street",
      city: "Los Angeles",
      phone: "+1 877-555-9615",
      status: "rejected",
      createdAt: "2025-01-01T23:00:00Z",
    },
    {
      id: "10",
      title: "Midland Credit",
      email: "info10@midlandcredit.com",
      password: "pass10@",
      description: "Dedicated to personal and business banking excellence.",
      address: "250 Elm Street",
      city: "Houston",
      phone: "+1 507-555-7520",
      status: "approved",
      createdAt: "2025-02-15T11:00:00Z",
    },
    {
      id: "11",
      title: "Pioneer Credit Bank",
      email: "info11@pioneercreditbank.com",
      password: "pass11#",
      description: "Empowering financial growth and security.",
      address: "477 Pine Street",
      city: "Los Angeles",
      phone: "+1 524-555-9319",
      status: "pending",
      createdAt: "2025-02-20T00:00:00Z",
    },
    {
      id: "12",
      title: "Pacific Trust",
      email: "info12@pacifictrust.com",
      password: "pass12@",
      description: "Rooted in tradition, focused on the future.",
      address: "910 Pine Street",
      city: "Houston",
      phone: "+1 736-555-8274",
      status: "rejected",
      createdAt: "2025-03-15T15:00:00Z",
    },
    {
      id: "13",
      title: "United Finance",
      email: "info13@unitedfinance.com",
      password: "pass13#",
      description: "Rooted in tradition, focused on the future.",
      address: "667 Elm Street",
      city: "San Antonio",
      phone: "+1 475-555-8131",
      status: "rejected",
      createdAt: "2025-04-22T18:00:00Z",
    },
    {
      id: "14",
      title: "Global Trust Bank",
      email: "info14@globaltrustbank.com",
      password: "pass14@",
      description: "Rooted in tradition, focused on the future.",
      address: "590 Pine Street",
      city: "San Diego",
      phone: "+1 225-555-3286",
      status: "approved",
      createdAt: "2025-04-02T23:00:00Z",
    },
    {
      id: "15",
      title: "Secure Capital",
      email: "info15@securecapital.com",
      password: "pass15@",
      description: "Rooted in tradition, focused on the future.",
      address: "388 Maple Street",
      city: "San Diego",
      phone: "+1 709-555-4208",
      status: "pending",
      createdAt: "2025-01-27T06:00:00Z",
    },
    {
      id: "16",
      title: "Evergreen Bank",
      email: "info16@evergreenbank.com",
      password: "pass16!",
      description: "Innovative banking solutions for modern customers.",
      address: "409 Maple Street",
      city: "Philadelphia",
      phone: "+1 507-555-4735",
      status: "approved",
      createdAt: "2024-12-09T16:00:00Z",
    },
    {
      id: "17",
      title: "Harmony Bank",
      email: "info17@harmonybank.com",
      password: "pass17#",
      description: "Serving communities for over 50 years.",
      address: "471 Maple Street",
      city: "San Diego",
      phone: "+1 643-555-1778",
      status: "pending",
      createdAt: "2025-02-14T23:00:00Z",
    },
    {
      id: "18",
      title: "NextGen Bank",
      email: "info18@nextgenbank.com",
      password: "pass18!",
      description: "Serving communities for over 50 years.",
      address: "780 Maple Street",
      city: "Dallas",
      phone: "+1 317-555-3403",
      status: "rejected",
      createdAt: "2025-01-02T04:00:00Z",
    },
    {
      id: "19",
      title: "Pioneer Credit Bank",
      email: "info19@pioneercreditbank.com",
      password: "pass19!",
      description: "A reliable bank for all your financial needs.",
      address: "610 Maple Street",
      city: "New York",
      phone: "+1 580-555-4061",
      status: "approved",
      createdAt: "2025-04-28T16:00:00Z",
    },
    {
      id: "20",
      title: "Pacific Trust",
      email: "info20@pacifictrust.com",
      password: "pass20@",
      description: "Your community’s most dependable bank.",
      address: "298 Pine Street",
      city: "San Diego",
      phone: "+1 506-555-3013",
      status: "rejected",
      createdAt: "2025-02-19T15:00:00Z",
    },
    {
      id: "21",
      title: "Heritage Savings",
      email: "info21@heritagesavings.com",
      password: "pass21!",
      description: "A reliable bank for all your financial needs.",
      address: "586 Oak Street",
      city: "San Antonio",
      phone: "+1 768-555-7223",
      status: "pending",
      createdAt: "2025-03-03T20:00:00Z",
    },
    {
      id: "22",
      title: "Harmony Bank",
      email: "info22@harmonybank.com",
      password: "pass22!",
      description: "Your community’s most dependable bank.",
      address: "637 Pine Street",
      city: "San Antonio",
      phone: "+1 460-555-6857",
      status: "approved",
      createdAt: "2025-01-26T00:00:00Z",
    },
    {
      id: "23",
      title: "Heritage Savings",
      email: "info23@heritagesavings.com",
      password: "pass23@",
      description: "Committed to transparency and innovation.",
      address: "892 Maple Street",
      city: "San Diego",
      phone: "+1 225-555-9573",
      status: "rejected",
      createdAt: "2025-01-03T18:00:00Z",
    },
    {
      id: "24",
      title: "First National Bank",
      email: "info24@firstnationalbank.com",
      password: "pass24#",
      description: "Award-winning service and nationwide branches.",
      address: "623 Maple Street",
      city: "New York",
      phone: "+1 241-555-5781",
      status: "pending",
      createdAt: "2025-01-04T14:00:00Z",
    },
    {
      id: "25",
      title: "Harmony Bank",
      email: "info25@harmonybank.com",
      password: "pass25!",
      description: "Rooted in tradition, focused on the future.",
      address: "510 Elm Street",
      city: "Phoenix",
      phone: "+1 752-555-7478",
      status: "pending",
      createdAt: "2025-04-17T04:00:00Z",
    },
    {
      id: "26",
      title: "Pacific Trust",
      email: "info26@pacifictrust.com",
      password: "pass26#",
      description: "Serving communities for over 50 years.",
      address: "652 Maple Street",
      city: "Houston",
      phone: "+1 398-555-7474",
      status: "approved",
      createdAt: "2025-04-06T11:00:00Z",
    },
    {
      id: "27",
      title: "First National Bank",
      email: "info27@firstnationalbank.com",
      password: "pass27#",
      description: "Your community’s most dependable bank.",
      address: "667 Elm Street",
      city: "Phoenix",
      phone: "+1 280-555-1711",
      status: "approved",
      createdAt: "2024-12-19T00:00:00Z",
    },
    {
      id: "28",
      title: "NextGen Bank",
      email: "info28@nextgenbank.com",
      password: "pass28!",
      description: "Award-winning service and nationwide branches.",
      address: "879 Maple Street",
      city: "San Diego",
      phone: "+1 462-555-5643",
      status: "approved",
      createdAt: "2024-12-17T11:00:00Z",
    },
    {
      id: "29",
      title: "Guardian Financial",
      email: "info29@guardianfinancial.com",
      password: "pass29@",
      description: "Innovative banking solutions for modern customers.",
      address: "732 Oak Street",
      city: "Chicago",
      phone: "+1 632-555-6687",
      status: "approved",
      createdAt: "2025-01-23T10:00:00Z",
    },
    {
      id: "30",
      title: "Sunrise Financial",
      email: "info30@sunrisefinancial.com",
      password: "pass30@",
      description: "A reliable bank for all your financial needs.",
      address: "426 Elm Street",
      city: "Philadelphia",
      phone: "+1 627-555-1800",
      status: "approved",
      createdAt: "2025-04-03T21:00:00Z",
    },
    {
      id: "31",
      title: "Alliance Bank",
      email: "info31@alliancebank.com",
      password: "pass31!",
      description: "Your community’s most dependable bank.",
      address: "253 Elm Street",
      city: "Houston",
      phone: "+1 432-555-8311",
      status: "rejected",
      createdAt: "2024-12-20T18:00:00Z",
    },
    {
      id: "32",
      title: "First National Bank",
      email: "info32@firstnationalbank.com",
      password: "pass32@",
      description: "Award-winning service and nationwide branches.",
      address: "355 Oak Street",
      city: "San Jose",
      phone: "+1 292-555-3203",
      status: "approved",
      createdAt: "2025-04-01T03:00:00Z",
    },
    {
      id: "33",
      title: "Heritage Savings",
      email: "info33@heritagesavings.com",
      password: "pass33!",
      description: "Empowering financial growth and security.",
      address: "430 Maple Street",
      city: "New York",
      phone: "+1 437-555-1851",
      status: "pending",
      createdAt: "2025-03-10T22:00:00Z",
    },
    {
      id: "34",
      title: "Sunrise Financial",
      email: "info34@sunrisefinancial.com",
      password: "pass34@",
      description: "Your community’s most dependable bank.",
      address: "102 Pine Street",
      city: "San Antonio",
      phone: "+1 602-555-6705",
      status: "pending",
      createdAt: "2024-12-21T23:00:00Z",
    },
    {
      id: "35",
      title: "Summit Bank",
      email: "info35@summitbank.com",
      password: "pass35!",
      description: "Rooted in tradition, focused on the future.",
      address: "622 Elm Street",
      city: "Phoenix",
      phone: "+1 785-555-1435",
      status: "pending",
      createdAt: "2024-12-24T04:00:00Z",
    },
    {
      id: "36",
      title: "Midland Credit",
      email: "info36@midlandcredit.com",
      password: "pass36#",
      description: "Empowering financial growth and security.",
      address: "421 Pine Street",
      city: "Dallas",
      phone: "+1 220-555-7783",
      status: "pending",
      createdAt: "2024-12-29T23:00:00Z",
    },
    {
      id: "37",
      title: "Alliance Bank",
      email: "info37@alliancebank.com",
      password: "pass37!",
      description: "Innovative banking solutions for modern customers.",
      address: "332 Maple Street",
      city: "Houston",
      phone: "+1 838-555-4829",
      status: "pending",
      createdAt: "2024-12-14T14:00:00Z",
    },
    {
      id: "38",
      title: "Sunrise Financial",
      email: "info38@sunrisefinancial.com",
      password: "pass38!",
      description: "Trusted partner in local and international finance.",
      address: "584 Pine Street",
      city: "Houston",
      phone: "+1 686-555-7207",
      status: "approved",
      createdAt: "2025-03-18T19:00:00Z",
    },
    {
      id: "39",
      title: "Sunrise Financial",
      email: "info39@sunrisefinancial.com",
      password: "pass39@",
      description: "Rooted in tradition, focused on the future.",
      address: "285 Maple Street",
      city: "Houston",
      phone: "+1 357-555-3403",
      status: "approved",
      createdAt: "2025-02-26T07:00:00Z",
    },
    {
      id: "40",
      title: "Summit Bank",
      email: "info40@summitbank.com",
      password: "pass40@",
      description: "Award-winning service and nationwide branches.",
      address: "291 Elm Street",
      city: "Chicago",
      phone: "+1 521-555-8841",
      status: "pending",
      createdAt: "2025-03-19T00:00:00Z",
    },
    {
      id: "41",
      title: "Alliance Bank",
      email: "info41@alliancebank.com",
      password: "pass41#",
      description: "Trusted partner in local and international finance.",
      address: "268 Oak Street",
      city: "Houston",
      phone: "+1 732-555-5557",
      status: "approved",
      createdAt: "2025-04-20T10:00:00Z",
    },
    {
      id: "42",
      title: "Heritage Savings",
      email: "info42@heritagesavings.com",
      password: "pass42#",
      description: "Dedicated to personal and business banking excellence.",
      address: "236 Oak Street",
      city: "Phoenix",
      phone: "+1 292-555-3180",
      status: "rejected",
      createdAt: "2025-01-16T15:00:00Z",
    },
    {
      id: "43",
      title: "Liberty Bank",
      email: "info43@libertybank.com",
      password: "pass43#",
      description: "Award-winning service and nationwide branches.",
      address: "556 Oak Street",
      city: "San Antonio",
      phone: "+1 652-555-9422",
      status: "approved",
      createdAt: "2024-12-05T14:00:00Z",
    },
  ];
  