export const requestData = [
  {
    id: 1,
    name: "Aye Min",
    phone: "0912345678",
    email: "ayemin@gmail.com",
    address: "Yangon",
    age: 29,
    blood_type: "A+",
    unit: 2,
    status: "pending",
  },
  {
    id: 2,
    name: "Su Mon",
    phone: "0919876543",
    email: "sumon@example.com",
    address: "Mandalay",
    age: 35,
    blood_type: "B+",
    unit: 1,
    status: "approved",
  },
  {
    id: 3,
    name: "Ko Ko",
    phone: "0923456789",
    email: "koko@yahoo.com",
    address: "Naypyidaw",
    age: 41,
    blood_type: "O-",
    unit: 3,
    status: "pending",
  },
  {
    id: 4,
    name: "Moe Moe",
    phone: "0976543210",
    email: "moemoe@gmail.com",
    address: "Bago",
    age: 26,
    blood_type: "AB+",
    unit: 2,
    status: "rejected",
  },
  {
    id: 5,
    name: "Tun Tun",
    phone: "0934567890",
    email: "tuntun@example.com",
    address: "Taunggyi",
    age: 33,
    blood_type: "O+",
    unit: 1,
    status: "pending",
  },
  {
    id: 6,
    name: "Zaw Win",
    phone: "0912341122",
    email: "zawwin@gmail.com",
    address: "Yangon",
    age: 45,
    blood_type: "A-",
    unit: 2,
    status: "approved",
  },
  {
    id: 7,
    name: "Cherry Hnin",
    phone: "0966112233",
    email: "cherryhnin@example.com",
    address: "Myeik",
    age: 38,
    blood_type: "B-",
    unit: 1,
    status: "pending",
  },
  {
    id: 8,
    name: "Min Khant",
    phone: "0998877665",
    email: "mkhant@gmail.com",
    address: "Pathein",
    age: 22,
    blood_type: "AB-",
    unit: 2,
    status: "approved",
  },
  {
    id: 9,
    name: "Shwe Yee",
    phone: "0944221133",
    email: "shweyee@hotmail.com",
    address: "Pyin Oo Lwin",
    age: 27,
    blood_type: "O+",
    unit: 1,
    status: "rejected",
  },
  {
    id: 10,
    name: "Aung Aung",
    phone: "0922113344",
    email: "aungaung@gmail.com",
    address: "Magway",
    age: 31,
    blood_type: "A+",
    unit: 3,
    status: "pending",
  },
  {
    id: 11,
    name: "Thandar",
    phone: "0955998877",
    email: "thandar@gmail.com",
    address: "Yangon",
    age: 24,
    blood_type: "B+",
    unit: 2,
    status: "pending",
  },
  {
    id: 12,
    name: "Htet Wai",
    phone: "0911223344",
    email: "htetwai@gmail.com",
    address: "Meiktila",
    age: 37,
    blood_type: "O-",
    unit: 1,
    status: "approved",
  },
  {
    id: 13,
    name: "Yadanar",
    phone: "0933445566",
    email: "yadanar@ymail.com",
    address: "Hpa-An",
    age: 30,
    blood_type: "AB+",
    unit: 2,
    status: "pending",
  },
  {
    id: 14,
    name: "Thura",
    phone: "0977554433",
    email: "thura@example.com",
    address: "Sagaing",
    age: 44,
    blood_type: "A-",
    unit: 1,
    status: "approved",
  },
  {
    id: 15,
    name: "Ei Mon",
    phone: "0944332211",
    email: "eimon@gmail.com",
    address: "Myitkyina",
    age: 28,
    blood_type: "B-",
    unit: 3,
    status: "pending",
  },
  {
    id: 16,
    name: "Nyein Chan",
    phone: "0966554433",
    email: "nyeinchan@outlook.com",
    address: "Pyay",
    age: 36,
    blood_type: "O+",
    unit: 2,
    status: "pending",
  },
  {
    id: 17,
    name: "Mya Hnin",
    phone: "0911225566",
    email: "myahnin@example.com",
    address: "Bago",
    age: 39,
    blood_type: "AB-",
    unit: 1,
    status: "rejected",
  },
  {
    id: 18,
    name: "Bo Bo",
    phone: "0912889900",
    email: "bobo@gmail.com",
    address: "Dawei",
    age: 33,
    blood_type: "A+",
    unit: 2,
    status: "approved",
  },
  {
    id: 19,
    name: "Khine Su",
    phone: "0922887755",
    email: "khinesu@example.com",
    address: "Sittwe",
    age: 21,
    blood_type: "B+",
    unit: 1,
    status: "pending",
  },
  {
    id: 20,
    name: "Kyaw Win",
    phone: "0955443322",
    email: "kyawwin@gmail.com",
    address: "Taungoo",
    age: 40,
    blood_type: "O-",
    unit: 2,
    status: "rejected",
  },
  {
    id: 21,
    name: "Lay Lay",
    phone: "0933664422",
    email: "laylay@gmail.com",
    address: "Lashio",
    age: 27,
    blood_type: "AB+",
    unit: 1,
    status: "pending",
  },
  {
    id: 22,
    name: "Kaung Htet",
    phone: "0944776655",
    email: "kaunghtet@example.com",
    address: "Prome",
    age: 32,
    blood_type: "A-",
    unit: 2,
    status: "approved",
  },
  {
    id: 23,
    name: "Hnin Thiri",
    phone: "0911773344",
    email: "hninthiri@gmail.com",
    address: "Yangon",
    age: 23,
    blood_type: "B-",
    unit: 1,
    status: "pending",
  },
  {
    id: 24,
    name: "Zaw Moe",
    phone: "0966221133",
    email: "zawmoe@example.com",
    address: "Mawlamyine",
    age: 43,
    blood_type: "O+",
    unit: 3,
    status: "rejected",
  },
  {
    id: 25,
    name: "Aung Myint",
    phone: "0922998877",
    email: "aungmyint@gmail.com",
    address: "Pathein",
    age: 35,
    blood_type: "AB-",
    unit: 2,
    status: "approved",
  },
  {
    id: 26,
    name: "Su Wai",
    phone: "0955773322",
    email: "suwai@example.com",
    address: "Yenangyaung",
    age: 31,
    blood_type: "A+",
    unit: 1,
    status: "pending",
  },
  {
    id: 27,
    name: "Win Htet",
    phone: "0977665544",
    email: "winhtet@gmail.com",
    address: "Myingyan",
    age: 29,
    blood_type: "B+",
    unit: 2,
    status: "pending",
  },
  {
    id: 28,
    name: "Thazin",
    phone: "0933778899",
    email: "thazin@example.com",
    address: "Hinthada",
    age: 26,
    blood_type: "O-",
    unit: 1,
    status: "approved",
  },
  {
    id: 29,
    name: "Sai Moe",
    phone: "0944556677",
    email: "saimoe@gmail.com",
    address: "Kengtung",
    age: 42,
    blood_type: "AB+",
    unit: 2,
    status: "rejected",
  },
  {
    id: 30,
    name: "Chan Nyein",
    phone: "0911882233",
    email: "channyein@example.com",
    address: "Thayet",
    age: 34,
    blood_type: "A-",
    unit: 1,
    status: "pending",
  },
  {
    id: 31,
    name: "Mya Mya",
    phone: "0922114455",
    email: "myamya@gmail.com",
    address: "Loikaw",
    age: 25,
    blood_type: "B-",
    unit: 2,
    status: "approved",
  },
  {
    id: 32,
    name: "Paing Soe",
    phone: "0955332211",
    email: "paingsoe@example.com",
    address: "Shwebo",
    age: 39,
    blood_type: "O+",
    unit: 1,
    status: "pending",
  },
  {
    id: 33,
    name: "Su Htet",
    phone: "0977334455",
    email: "suhtet@gmail.com",
    address: "Pakokku",
    age: 30,
    blood_type: "AB-",
    unit: 3,
    status: "pending",
  },
  {
    id: 34,
    name: "Ye Yint",
    phone: "0966998877",
    email: "yeyint@example.com",
    address: "Pyinmana",
    age: 28,
    blood_type: "A+",
    unit: 2,
    status: "approved",
  },
  {
    id: 35,
    name: "Khine Win",
    phone: "0912341234",
    email: "khinewin@gmail.com",
    address: "Yamethin",
    age: 36,
    blood_type: "B+",
    unit: 1,
    status: "pending",
  },
];
